### ISSUE TITLE
How to insert the token in the form

### ISSUE THREAD

**Issue by netwarp** [kemalcr/kemal-csrf#17]
I would like to know how to insert the token in the form:
`<input type="hidden" name="_csrf" value="<%= env.session.csrf %>">`
This doen't work.
Thanks.

**Comment by MisterBianco** [comment]
I am not sure why no one has answered this till now. I am a little disappointed, however, after spending some time looking at other implementations I have found a method that works for me and I hope works for you.

```
<input type="hidden" name="_csrf" value="<%= env.session.string("csrf") %>">
```

**Comment by sdogruyol** [comment]
Thanks @MisterBianco :+1: I've added a subsection to Kemal Guide http://kemalcr.com/guide/#sessions

**Comment by greenbigfrog** [comment]
FYI: The default parameter name is `authenticity_token`, so your code should be:
```html
<input type="hidden" name="authenticity_token" value="<%= env.session.string("csrf") %>"/>
```

I've submitted a PR to fix this in the Guide: https://github.com/kemalcr/kemal-csrf/blob/master/src/kemal-csrf.cr#L14
