### ISSUE TITLE
CSRF with Multi Part forms

### ISSUE THREAD

**Issue by crisward** [kemalcr/kemal-csrf#3]
The csrf attribute isn't read with multipart forms.
I'll try and add this as a pull request if I can.

**Comment by sdogruyol** [comment]
@crisward thank you 🙏

**Comment by crisward** [comment]
Had a quick mess with this. The problem with reading multi-part inside csrf is it's no longer available for the end app.

I think in other languages multipart is done as middleware. Copying the data into the same place as normal form values, so writing the form fields to `context.params.body`. File data would be streamed to a temp directory and then the files meta properties also copied to `context.params.body`.

When the final app goes to utilise the uploaded files, they can just move the files.

With that in mind. You can close this issue as I'll create a multi-part middleware which can run before csrf, then csrf will just need to read from `context.params.body` which it already does.

What do you think?

**Comment by crisward** [comment]
I've got this working. However middleware wouldn't cut it. I needed to patch `Kemal::ParamParser` parse_body method.

I've basically added a files hash to `context.params`. This contains a hash of `Kemal::UploadedFile` (not to be mixed up with Kemal:UploadFile from your helpers). With the key of the field name.

These uploadedfiles have three properties. tmpfile, filename, headers.

So to handle uploads you would
```crystal
post "/uploads" do |ctx|
  uploadpath = "images/"
  ctx.params.files.each do |field, file|
    file_path = ::File.join [Kemal.config.public_folder, uploadpath, file.filename]
    ::File.rename(file.tmpfile, file_path)
  end
end
```
or if you only want one specific file

```crystal
post "/uploads" do |ctx|
  file = ctx.params.files["myfile"]
  file_path = ::File.join [Kemal.config.public_folder, "images/", file.filename]
  ::File.rename(file.tmpfile, file_path)
end
```

This also adds all non-file fields to `context.params.body` so fixes the csrf issue.

The tempfile is using Crystals `Tempfile`, which I'm guessing saves to /tmp by default. These tmp files will probably need cleaning up occasionally. Not sure if you have any ideas for this, I noticed you had a garbage collector in the kemal-session to delete old sessions. Perhaps we could do something similar here.
 
What do you think? Would you like me to create a pull request for kemal. Or leave this as a separate module?

Thanks.

**Comment by crisward** [comment]
Actually the file clean up could be called around here - https://github.com/kemalcr/kemal/blob/master/src/kemal/route_handler.cr#L37

After the route has finished, any tmp files still remaining could be deleted?

**Comment by crisward** [comment]
I'll close this now as it was fixed in kemal

**Comment by sdogruyol** [comment]
@crisward Thank you 👍
